In [2]:
# Lectura de datos
import pandas as pd

# import numpy as np

In [3]:
print("--- RawData loaded ---")
df = pd.read_csv("../test_data/iris.csv", header=None)
df

--- RawData loaded ---


0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

### EDA

In [11]:
# Aplicamos el dropna a cualquier valor nulo
df.dropna(how='any', inplace=True)

In [ ]:
# Aplicar el estudio de la distribución

In [ ]:
# Aplicar el paso de imputación de los valores 

In [4]:
# columns
cols = ['sepal_length', 'sepal_width',
        'petal_length', 'petal_width']

In [5]:
# Matriz de features
X = df.iloc[:, :-1].values

# variable dep.
y = df.iloc[:, -1]
print("--- Matrix loaded ---")

--- Matrix loaded ---


In [6]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [7]:
y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: 4, Length: 150, dtype: object

In [8]:
# Creamos la instancia de LabelEncoder para la var. dep.
from sklearn.preprocessing import LabelEncoder

In [9]:
# Creamos el encoder
encoder = LabelEncoder()
y_enc = encoder.fit_transform(y)
print("--- LabelEncoder loaded ---")

--- LabelEncoder loaded ---


In [10]:
y_enc

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
encoder.

In [78]:
# Modelamos con el paso de Train and Test split
from sklearn.model_selection import train_test_split

seed = 17

X_train, X_test, y_train, y_test = train_test_split(X, y_enc, 
                                                    test_size=0.35,
                                                    random_state=seed)
print("--- TrainTest loaded ---")

--- TrainTest loaded ---


In [79]:
X_train

array([[6.7, 3. , 5. , 1.7],
       [5.6, 2.7, 4.2, 1.3],
       [4.4, 3.2, 1.3, 0.2],
       [6.9, 3.1, 4.9, 1.5],
       [5.8, 2.7, 5.1, 1.9],
       [6.5, 3. , 5.8, 2.2],
       [5. , 3.5, 1.3, 0.3],
       [5. , 3.6, 1.4, 0.2],
       [7.4, 2.8, 6.1, 1.9],
       [4.9, 3. , 1.4, 0.2],
       [6. , 2.2, 5. , 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [5.7, 3.8, 1.7, 0.3],
       [6.4, 3.1, 5.5, 1.8],
       [4.8, 3.4, 1.9, 0.2],
       [5.8, 4. , 1.2, 0.2],
       [6. , 2.2, 4. , 1. ],
       [7.2, 3.6, 6.1, 2.5],
       [5. , 3.5, 1.6, 0.6],
       [5.1, 3.8, 1.6, 0.2],
       [6.7, 3.1, 4.4, 1.4],
       [4.8, 3. , 1.4, 0.3],
       [6.5, 3. , 5.2, 2. ],
       [7.1, 3. , 5.9, 2.1],
       [4.6, 3.2, 1.4, 0.2],
       [5.5, 4.2, 1.4, 0.2],
       [5.2, 2.7, 3.9, 1.4],
       [6.7, 3.1, 5.6, 2.4],
       [7.6, 3. , 6.6, 2.1],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3. , 1.6, 0.2],
       [6.3, 3.4, 5.6, 2.4],
       [4.8, 3. , 1.4, 0.1],
       [5.1, 3.7, 1.5, 0.4],
       [6.9, 3

In [80]:
# Utilizamos el primer modelo - baseline
from sklearn.neighbors import KNeighborsClassifier

In [81]:
# Configuración del algoritmo o estimador
classifier = KNeighborsClassifier(n_neighbors=5,
                                  metric="minkowski",
                                  p=2)

# Ajustamos el estimador a los datos de entrenamiento
classifier.fit(X_train, y_train)
print("--- TrainTest loaded ---")

--- TrainTest loaded ---


In [92]:
X_test

array([5.4, 3.9, 1.3, 0.4])

In [83]:
# Realizamos la predicción
y_pred = classifier.predict(X_test)
print("--- Predictions loaded ---")

--- Predictions loaded ---


In [93]:
X_test[0]

array([5.4, 3.9, 1.3, 0.4])

In [84]:
y_pred

array([0, 1, 2, 1, 2, 1, 1, 2, 1, 2, 2, 0, 1, 0, 2, 0, 0, 2, 2, 2, 1, 0,
       2, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 2, 1, 0, 1, 1, 0, 1,
       2, 1, 1, 2, 1, 0, 2, 1, 1])

In [85]:
# Métricas del modelo
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_true = y_test,
                          y_pred = y_pred)
print(f"Accuracy Score: {round(accuracy*100,2)}")

Accuracy Score: 96.23


In [87]:
# Guardamos el serializado del transformer y el modelo
import joblib
#import pickle

# Para serializar un artefacto
path = "../models/iris_label_encoder.pkl"
joblib.dump(encoder, open(path, 'wb'))

In [88]:
# Cargamos el artefacto como prueba
joblib.load(open(path, 'rb'))

LabelEncoder()

In [89]:
# Para serializar un artefacto del tipo modelo
path = "../models/iris_knn.pkl"
joblib.dump(classifier, open(path, 'wb'))

In [90]:
# Cargamos el artefacto como prueba
joblib.load(open(path, 'rb'))

KNeighborsClassifier()

In [91]:
print(" --- Pickle classifier dump executed ---")

 --- Pickle classifier dump executed ---


## Prueba Modelo en la web-app

In [106]:
X_test[0]

array([5.4, 3.9, 1.3, 0.4])

In [125]:
X_test

array([[5.4, 3.9, 1.3, 0.4],
       [6. , 2.9, 4.5, 1.5],
       [6.7, 3. , 5.2, 2.3],
       [5.7, 2.8, 4.1, 1.3],
       [6.2, 2.8, 4.8, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [5.4, 3. , 4.5, 1.5],
       [7.7, 3.8, 6.7, 2.2],
       [5.5, 2.4, 3.8, 1.1],
       [5.7, 2.5, 5. , 2. ],
       [6.7, 3.3, 5.7, 2.5],
       [4.9, 3.1, 1.5, 0.1],
       [5.7, 2.8, 4.5, 1.3],
       [4.8, 3.4, 1.6, 0.2],
       [6.5, 3.2, 5.1, 2. ],
       [5.1, 3.8, 1.5, 0.3],
       [4.4, 3. , 1.3, 0.2],
       [6.5, 3. , 5.5, 1.8],
       [6.3, 3.3, 6. , 2.5],
       [6.4, 2.8, 5.6, 2.2],
       [6.3, 2.8, 5.1, 1.5],
       [5.2, 3.4, 1.4, 0.2],
       [5.9, 3. , 5.1, 1.8],
       [5.6, 2.5, 3.9, 1.1],
       [5.6, 3. , 4.5, 1.5],
       [6. , 3.4, 4.5, 1.6],
       [5.5, 2.3, 4. , 1.3],
       [6.1, 2.8, 4.7, 1.2],
       [5.1, 3.5, 1.4, 0.2],
       [5.8, 2.6, 4. , 1.2],
       [4.7, 3.2, 1.6, 0.2],
       [5.1, 2.5, 3. , 1.1],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.9, 1.7, 0.4],
       [5.5, 2

In [130]:
# Aplicamos la inversa del encoder para devolver el texto de la clase predicha
encoder.inverse_transform(classifier.predict(X_test[[50]]))[0]

'Iris-virginica'