# Instalar librerías en Python

In [ ]:
%%sh
pip install numpy -q

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.__version__

'1.24.3'

In [3]:
pd.__version__

'1.5.0'

In [4]:
!pip install --help


Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

Description:
  Install packages from:
  
  - PyPI (and other indexes) using requirement specifiers.
  - VCS project urls.
  - Local project directories.
  - Local or remote source archives.
  
  pip also supports installing from "requirements files", which provide
  an easy way to specify a whole environment to be installed.

Install Options:
  -r, --requirement <file>    Install from the given requirements file. This
                              option can be used multiple times.
  -c, --constraint <file>     Constrain versions using the given constraints
                              file. This option can be used multiple times.
  --no-deps                   Don't install p

In [8]:
!dir

 El volumen de la unidad C no tiene etiqueta.
 El n�mero de serie del volumen es: 1219-5398

 Directorio de c:\Users\mrusso\PERSONAL\THE_BRIDGE_23_ALUMNI\01_RAMP_UP\week_02

26/04/2023  19:09    <DIR>          .
26/04/2023  19:09    <DIR>          ..
24/04/2023  21:20    <DIR>          labs
26/04/2023  19:22             1.661 python101_w02d2.ipynb
26/04/2023  19:08            22.497 python101_week02.ipynb
               2 archivos         24.158 bytes
               3 dirs  366.424.846.336 bytes libres


In [9]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [13]:
salarios = 10 ** np.random.uniform(2, 5, (1000,2000))

In [14]:
salarios

array([[  740.94601377,   472.75524052, 61062.02455999, ...,
         9248.12865061,   389.02803536, 64987.56628176],
       [  871.66770332, 20299.07220954, 11207.45491859, ...,
          226.42168049,  9719.76606782, 33364.28256704],
       [87467.2688959 ,   182.10897796,  2981.01024321, ...,
        17587.06637087,   121.41734986,   231.0630646 ],
       ...,
       [34230.28496198, 11916.33494223, 58476.12144187, ...,
         8053.33382895,   789.96139496,  2320.53899003],
       [ 1696.45791565,  2074.86433383,  2102.85935903, ...,
        40113.16989338,  4233.82501467,  8772.31682522],
       [80681.92630088, 20676.11873659, 62676.24260947, ...,
         2501.37449874, 32481.70716104,  1403.4629589 ]])

In [15]:
type(salarios)

numpy.ndarray

In [16]:
for salario in salarios:
    print(salario)
    break;

[  740.94601377   472.75524052 61062.02455999 ...  9248.12865061
   389.02803536 64987.56628176]


In [17]:
nombre = 'Rafael'
edad = 40

In [18]:
dir(nombre)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',


In [20]:
# utilizando for sobre una lista iterando elemento por elemento 
# para extraer los métodos 
for method in dir(nombre):
    if not method.startswith("__"):
        print(method)

# O bien puedo utilizar list comprehension
[method for method in dir(nombre) if not method.startswith("__")]

capitalize
casefold
center
count
encode
endswith
expandtabs
find
format
format_map
index
isalnum
isalpha
isascii
isdecimal
isdigit
isidentifier
islower
isnumeric
isprintable
isspace
istitle
isupper
join
ljust
lower
lstrip
maketrans
partition
removeprefix
removesuffix
replace
rfind
rindex
rjust
rpartition
rsplit
rstrip
split
splitlines
startswith
strip
swapcase
title
translate
upper
zfill


['capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [21]:
# set recoge los valores únicos y list convierte el set en una lista nueva
lista_metodos_string = list(set([method for method in dir(nombre) if not method.startswith("__")]))
lista_metodos_string

['capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'removeprefix',
 'removesuffix',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',
 'zfill']

In [22]:
paises = ['Alemania', 'Francia', 'España', 'Italia']
paises

['Alemania', 'Francia', 'España', 'Italia']

In [24]:
paises.append('Alemania')
paises

['Alemania', 'Francia', 'España', 'Italia', 'Alemania', 'Alemania']

In [25]:
paises_unicos = set(paises)
paises_unicos

{'Alemania', 'España', 'Francia', 'Italia'}

In [26]:
paises_unicos_2 = {"España", "Francia", "Italia", "Italia", 'Francia'}
paises_unicos_2

{'España', 'Francia', 'Italia'}

In [27]:
paises_unicos.union(paises_unicos_2)

{'Alemania', 'España', 'Francia', 'Italia'}

In [28]:
paises_unicos.intersection(paises_unicos_2)

{'España', 'Francia', 'Italia'}

In [30]:
paises_unicos.difference(paises_unicos_2)

{'Alemania'}

In [34]:
# Convertimos un set a lisat
list(paises_unicos_2)

['Italia', 'España', 'Francia']

## Range ... Enumerate

In [36]:
for n in range(1,20):
    print(n)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [37]:
for num in range(0,101,2):
    print(num)

0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98
100


In [38]:
max_num = 10
contador = 0
while contador <= max_num:
    print(contador)
    contador += 1

0
1
2
3
4
5
6
7
8
9
10


In [39]:
for idx, paises in enumerate(paises_unicos):
    print(idx, paises)

0 Italia
1 España
2 Francia
3 Alemania


In [45]:
for pais in list(paises_unicos_2):
    idx = list(paises_unicos_2).index(pais)
    print(idx, pais)

0 Italia
1 España
2 Francia


## Funciones UDF (User Defined Function)

Al crear funciones definidas por nosotros, también se utilizan funciones de librerías y built-in

In [46]:
# Problema: Calcular la edad basada en la fecha de nacimiento
years = [1964, 1971, 1981, 1990, 2001, 2004]


In [47]:
ages = []
for anyo in years:
    age = 2023 - anyo
    ages.append(age)

print(ages)

[59, 52, 42, 33, 22, 19]


In [48]:
ages_sum = sum(ages)
ages_sum

227

In [49]:
n_people = len(ages)
n_people

6

In [50]:
age_mean = ages_sum / n_people
age_mean

37.833333333333336

## ¿ Cómo podemos mejorar este proceso?

Creamos una función que basada del año actual `datetime` calcula la edad media redondeada de las personas de un determinado listado de n elementos data el año de nacimiento. 

### Pasamos a crear la función

```
def nombre_funcion(param1, param2, param3=None, param4=0):
     """
        random(size=None, dtype=np.float64, out=None)
        Return random floats in the half-open interval [0.0, 1.0).
        Results are from the "continuous uniform" distribution over the
        stated interval.  To sample :math:`Unif[a, b), b > a` use `uniform`
        or multiply the output of `random` by ``(b - a)`` and add ``a``::
            (b - a) * random() + a
        Parameters
        ----------
        size : int or tuple of ints, optional
            Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
            ``m * n * k`` samples are drawn.  Default is None, in which case a
            single value is returned.
        dtype : dtype, optional
            Desired dtype of the result, only `float64` and `float32` are supported.
            Byteorder must be native. The default value is np.float64.
        out : ndarray, optional
            Alternative output array in which to place the result. If size is not None,
            it must have the same shape as the provided size and must match the type of
            the output values.
        Returns
        -------
        out : float or ndarray of floats
            Array of random floats of shape `size` (unless ``size=None``, in which
            case a single float is returned).
        See Also
        --------
        uniform : Draw samples from the parameterized uniform distribution.
        Examples
        --------
        >>> rng = np.random.default_rng()
        >>> rng.random()
        0.47108547995356098 # random
        >>> type(rng.random())
        <class 'float'>
        >>> rng.random((5,))
        array([ 0.30220482,  0.86820401,  0.1654503 ,  0.11659149,  0.54323428]) # random
        Three-by-two array of random numbers from [-5, 0):
        >>> 5 * rng.random((3, 2)) - 5
        array([[-3.99149989, -0.52338984], # random
               [-2.99091858, -0.79479508],
               [-1.23204345, -1.75224494]])
        """

        # Comentario del statement
        ---- operaciones de una función


        return OUTPUT

        ```

In [57]:
### Pasamos a crear la función

def nombre_funcion(param1, param2, param3=None, param4=0):
    """
    random(size=None, dtype=np.float64, out=None)
    Return random floats in the half-open interval [0.0, 1.0).
    Results are from the "continuous uniform" distribution over the
    stated interval.  To sample :math:`Unif[a, b), b > a` use `uniform`
    or multiply the output of `random` by ``(b - a)`` and add ``a``::
    (b - a) * random() + a
    Parameters
    ----------
    size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
    dtype : dtype, optional
    Desired dtype of the result, only `float64` and `float32` are supported.
    Byteorder must be native. The default value is np.float64.
    out : ndarray, optional
    Alternative output array in which to place the result. If size is not None,
    it must have the same shape as the provided size and must match the type of
    the output values.
    Returns
    -------
    out : float or ndarray of floats
    Array of random floats of shape `size` (unless ``size=None``, in which
    case a single float is returned).
    See Also
    --------
    uniform : Draw samples from the parameterized uniform distribution.
    Examples
    --------
    """
    # CODIGO
    
    return param3

In [58]:
nombre_funcion()

TypeError: nombre_funcion() missing 2 required positional arguments: 'param1' and 'param2'

In [64]:
datetime.now().year

2023

In [65]:
datetime.today().year

2023

In [1]:
from datetime import datetime
def get_avg_age(birth_year):
    """
    Parameters:
    ----------
        birth_year list int
        
    Return:
    ------
        out float
    """
    
    '''
    Recogemos el valor year actual del datetime.today.year
    '''
    this_year = datetime.today().year # extrae el anyo
    
    # Calculamos las edades
    ages = []
    for anyo in birth_year:
        age = this_year - anyo
        ages.append(age)
    print("***"*20)
    print(ages) # mostramos el resultado parcial en pantalla

    # calculamos el promedio
    age_sum = sum(ages)
    n_people = len(ages)
    age_mean = age_sum / n_people

    print("/#"*20)

    # print(ages)
    return np.round(age_mean, 1)

In [67]:
get_avg_age(years)

************************************************************
[59, 52, 42, 33, 22, 19]
/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#


37.8

In [2]:
# Importamos la librerías desde el fichero exte
import utils

edades = [59, 52, 42, 33, 22, 19]

In [4]:
edad_avg, edad_max = utils.get_avg_age(edades)

************************************************************
[1964, 1971, 1981, 1990, 2001, 2004]
/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#/#
1985.2


In [5]:
edad_avg

1985.2

In [6]:
edad_max

2004